### ISSUE TITLE
Player Highlights jumbled, not associated with correct players.

### ISSUE THREAD

**Issue by droseispro** [philiannuzzo/fanlights#4] opened 2023-07-27 02:06 UTC
![Capture](https://github.com/philiannuzzo/fanlights/assets/140674981/f6c21ae1-0960-4804-9427-4dbc66d6ffde)

Came across this issue recently and thought I'd mention it.  Multiple video highlight icons are popping up (3 per player).  It's just a little out of sync and each one is not associated with the correct player.  Thanks!

**Comment by philiannuzzo** [comment] 2023-07-27 11:14
Could you please provide:

Browser/OS
League details
Steps to reproduce

Thanks,
Phil

**Comment by chefBrian** [comment] 2023-07-27 12:47
Not the original submitter, but 

-It's in Chrome as well as Firefox.
-Windows and Mac
-My league is public: https://baseball.fantasysports.yahoo.com/b1/58613
-You can go to any player on any page and click on their video icon (except the first in the array - the first one always works)

**Comment by philiannuzzo** [comment] 2023-07-28 18:26
Fixed in 2.1.6

Due to a repeated use of a class name by yahoo

**Closed as completed by philiannuzzo** 2023-07-28 18:26 UTC
Labels: bug
